name: Bug Report
description: Report a bug in ELVES
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.

  - type: input
    id: elves-version
    attributes:
      label: ELVES Version
      description: Which version of ELVES are you running?
      placeholder: "e.g., 0.6.0"
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: macOS Version
      description: Which macOS version are you on?
      placeholder: "e.g., macOS 14.2 (Sonoma)"
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: AI Runtime
      description: Which runtime were you using when the bug occurred?
      options:
        - Claude Code
        - Codex CLI
        - Both
        - N/A
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Open ELVES
        2. Type a task...
        3. Click summon...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem.
    validations:
      required: false
