name: Feature Request
description: Suggest a new feature for ELVES
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea to make the workshop better? We'd love to hear it!

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What problem are you trying to solve? What task would this help with?
      placeholder: "When I'm working on X, I need to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
      placeholder: "ELVES could..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, screenshots, or examples that help explain the feature.
    validations:
      required: false
